[package]
name = "verner-core"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "1.0.20"
anyhow = "1.0.79"
lazy_static = "1.4.0"
regex = "1.10.4"
serde = "1.0.197"
