name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare verner-git tests
      run: |
        git config --global user.email "git@git.git"
        git config --global user.name "Git Git"
        bash verner-git/setup-test.sh
    
    - name: Run tests
      run: cargo test --release --verbose
      
    - name: Build verner
      run: cargo build --bin verner --release --verbose
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: verner
        path: target/release/verner
        if-no-files-found: error
              
