name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run tests
      run: cargo test --verbose
      
    - name: Build verner
      run: cargo build --bin verner --release --verbose
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        # Artifact name
        name: verner
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/verner
        if-no-files-found: error
              
